docs_dir: docs/book
site_dir: docs/html
nav:
    - Home: index.md
    - "Progress Bars":
        - Intro: intro.md
        - Adapters: adapters.md
    - "File Upload Handlers": upload.md
site_name: zend-progressbar
site_description: "Create and update progress bars in different environments"
repo_url: 'https://github.com/zendframework/zend-progressbar'
